@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post/reaction
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "6368831f0ff06f817aebb84f",
  "postId": "636884850ff06f817aebb857",
  "type": "love",
  "previousReaction": "",
  "postReactions": {"like":0,"love":1,"happy":0,"sad":0,"angry":0},
  "profilePicture": "http://res.cloudinary.com/dxhu2wrmc/image/upload/v1667793696/6368831f0ff06f817aebb84f"
}

###
DELETE {{baseUrl}}/{{urlPath}}/post/reaction/636885fe45bcd9f28f9cc22e/love/{"like":0,"love":0,"happy":0,"sad":0,"angry":0}
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
GET  {{baseUrl}}/{{urlPath}}/post/reactions/636885fe45bcd9f28f9cc22e
Content-Type: application/json
Accept: application/json
withCredentials: true


###
GET  {{baseUrl}}/{{urlPath}}/post/signle/reaction/username/Manny/636885fe45bcd9f28f9cc22e
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET  {{baseUrl}}/{{urlPath}}/post/reactions/username/Manny
Content-Type: application/json
Accept: application/json
withCredentials: true